'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Mirrors HmacSignatureGuard's expected signing scheme exactly (see
// test/utils/signing.ts's signHmacRequest, used the same way in every
// e2e spec) — a load test that couldn't actually pass signature
// verification would just be measuring 401 responses, not the real
// charge path.
function signRequest(method, reqPath, bodyStr, hmacSecret) {
  const timestamp = String(Math.floor(Date.now() / 1000));
  const signedPayload = `${timestamp}.${method}.${reqPath}.${bodyStr}`;
  const signature = crypto.createHmac('sha256', hmacSecret).update(signedPayload).digest('hex');
  return { signature, timestamp };
}

// Spread load across many merchants rather than one — a single merchant's
// requests all share one MerchantThrottlerGuard bucket, which dominates the
// result almost immediately at any real load level (see
// docs/technical/load-testing.md's single-merchant run). Falls back to a
// single env-var-supplied merchant (LOAD_TEST_JWT/HMAC_SECRET/MERCHANT_ID)
// if .merchants.json hasn't been generated by setup-merchants.js — that's
// the deliberately-bottlenecked single-tenant scenario, not a bug.
let merchants = [];
try {
  merchants = JSON.parse(fs.readFileSync(path.join(__dirname, '.merchants.json'), 'utf8'));
} catch (e) {
  merchants = [{
    merchantId: process.env.LOAD_TEST_MERCHANT_ID,
    hmacSecret: process.env.LOAD_TEST_HMAC_SECRET,
    jwt: process.env.LOAD_TEST_JWT,
  }];
}

function pickMerchant() {
  return merchants[Math.floor(Math.random() * merchants.length)];
}

function signCharge(requestParams, context, ee, next) {
  const merchant = pickMerchant();
  context.vars.__merchant = merchant;

  const body = {
    // Random amount so requests aren't all identical — closer to real
    // traffic, and avoids any accidental short-circuiting on a fixed value.
    amount: Number((Math.random() * 490 + 10).toFixed(2)),
    currency: 'USD',
    paymentMethodId: 'pm_card_visa',
    orderId: 'loadtest_' + crypto.randomUUID(),
    binInfo: { bin: '424242', country: 'US', cardBrand: 'VISA', cardType: 'CREDIT' },
  };
  const bodyStr = JSON.stringify(body);
  const { signature, timestamp } = signRequest('POST', '/api/v1/payments/charge', bodyStr, merchant.hmacSecret);

  requestParams.headers = {
    ...requestParams.headers,
    Authorization: `Bearer ${merchant.jwt}`,
    // A fresh key per request — reusing one would make IdempotencyInterceptor
    // replay a cached response instead of exercising the real charge path,
    // silently making the app look far faster than it actually is.
    'Idempotency-Key': crypto.randomUUID(),
    'X-Signature': signature,
    'X-Timestamp': timestamp,
    'X-Merchant-Id': merchant.merchantId,
    'Content-Type': 'application/json',
  };
  requestParams.json = body;
  return next();
}

function addAuthHeader(requestParams, context, ee, next) {
  // Same merchant the charge in this flow used — a payment is only
  // readable by the merchant that owns it (assertOwnership).
  const merchant = context.vars.__merchant || pickMerchant();
  requestParams.headers = {
    ...requestParams.headers,
    Authorization: `Bearer ${merchant.jwt}`,
  };
  return next();
}

module.exports = { signCharge, addAuthHeader };
